# -*- coding: utf-8 -*-
"""AI-agent-task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n48QBJEMyzy8CtzurNGPH4eKbwykMwHD
"""

!pip install -Uq openai-agents

import nest_asyncio
nest_asyncio.apply()

from google.colab import userdata

OPENROUTER_API_KEY = userdata.get("OPENROUTER_API_KEY")

import asyncio
from openai import AsyncOpenAI
from agents import Agent, OpenAIChatCompletionsModel, Runner, set_tracing_disabled

client = AsyncOpenAI(
    api_key=OPENROUTER_API_KEY,
    base_url=BASE_URL
)

set_tracing_disabled(disabled=True)

async def main():
    # This agent will use the custom LLM provider
    agent = Agent(
        name="Assistant",
        instructions="You only respond in short detailed.",
        model=OpenAIChatCompletionsModel(model=MODEL, openai_client=client),
    )

    result = await Runner.run(
        agent,
        "Tell me about samade747 on github.",
    )
    print(result.final_output)


if __name__ == "__main__":
    asyncio.run(main())