# -*- coding: utf-8 -*-
"""AI-agent-task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n7FS7vgpXkmvljnpka-jtI3ris7VoFpv
"""

!pip install -Uq openai-agents

import nest_asyncio
nest_asyncio.apply()

from google.colab import userdata

OPENROUTER_API_KEY = userdata.get("OPENROUTER_API_KEY")

#Reference: https://openrouter.ai/docs/quickstart

BASE_URL = "https://openrouter.ai/api/v1"
MODEL = "deepseek/deepseek-chat-v3-0324:free"

# Some other free models on 26th March:
# https://openrouter.ai/deepseek/deepseek-chat-v3-0324:free
# https://openrouter.ai/google/gemini-2.5-pro-exp-03-25:free

import requests
import json

response = requests.post(
  url=f"{BASE_URL}/chat/completions",
  headers={
    "Authorization": f"Bearer {OPENROUTER_API_KEY}",
  },
  data=json.dumps({
    "model": MODEL,
    "messages": [
      {
        "role": "user",
        "content": "findout samade747 github and give the valuation"
      }
    ]
  })
)

print(response.json())

data = response.json()
data['choices'][0]['message']['content']